name = "axioms_of_adaptivity"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["AxiomsOfAdaptivity"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "subverso"
git = "https://github.com/leanprover/subverso"
rev = "no-modules"

[[lean_lib]]
name = "AxiomsOfAdaptivity"
